// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxk2-VeDN-DTmYu16i9dIGrSYcNkztvEc',
    appId: '1:582895946348:web:53650fb73613821f41a649',
    messagingSenderId: '582895946348',
    projectId: 'chatapp-6a180',
    authDomain: 'chatapp-6a180.firebaseapp.com',
    storageBucket: 'chatapp-6a180.appspot.com',
    measurementId: 'G-PE357PBSH6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHOZz8kyUQtIGriPWicSqUS6bu1dtT5Qg',
    appId: '1:582895946348:android:72b011ee554f899f41a649',
    messagingSenderId: '582895946348',
    projectId: 'chatapp-6a180',
    storageBucket: 'chatapp-6a180.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPIHkIpveli0FTIFfXURrf0rOAO3K6vfQ',
    appId: '1:582895946348:ios:a6fd610ccbe8734941a649',
    messagingSenderId: '582895946348',
    projectId: 'chatapp-6a180',
    storageBucket: 'chatapp-6a180.appspot.com',
    iosBundleId: 'com.example.chattingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxk2-VeDN-DTmYu16i9dIGrSYcNkztvEc',
    appId: '1:582895946348:web:eb0a02d321e38eae41a649',
    messagingSenderId: '582895946348',
    projectId: 'chatapp-6a180',
    authDomain: 'chatapp-6a180.firebaseapp.com',
    storageBucket: 'chatapp-6a180.appspot.com',
    measurementId: 'G-JLM3BVXZC4',
  );
}
